version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package_assignment_3.zip .
      - cd ..
      - zip -g deployment_package_assignment_3.zip lambda_function.py
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deployment_package_assignment_3.zip s3://layers-bucekt/
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name my_func_assignmnt3_cicd --s3-bucket layers-bucekt --s3-key deployment_package_assignment_3.zip
      - echo "Deployment complete!"